is_debug: true

server:
  http:
    addr: 0.0.0.0:8081
  grpc:
    addr: 0.0.0.0:8082

storage:
  host: localhost
  port: 5432
  database: musiqueDB
  username: gxrlxv
  password: qwerty

jwt:
  access_token_ttl: 15m
  refresh_token_ttl: 30m
  signing_key: signing_key

hasher:
  salt: salt