is_debug: true

listen:
  type: tcp
  bind_ip: localhost
  port: 8080

storage:
  host: localhost
  port: 5432
  database: musiqueDB
  username: gxrlxv
  password: qwerty

jwt:
  access_token_ttl: 15m
  refresh_token_ttl: 30m
  signing_key: signing_key

hasher:
  salt: salt