is_debug: true

listen:
  type: port
  port: 1234

storage:
  host: localhost
  port: 5432
  database: musiqueDB
  username: gxrlxv
  password: qwerty

jwt:
  access_token_ttl: 15m
  refresh_token_ttl: 30m
  signing_key: salt