is_debug: true

listen:
  type: port
  port: 1234

storage:
  host: localhost
  port: 5432
  database: musiqueDB
  username: gxrlxv
  password: qwerty

test:
  access_token_ttl: 15
  refresh_token_ttl: 30
  signing_key: salt

jwt:
  access_token_ttl: 15
  refresh_token_ttl: 30
  signing_key: salt